### ISSUE TITLE
Unable to get macro recording to work

### ISSUE THREAD

**Issue by ChristopherBare** [igorbb/MacroW#1]
I cannot get the macro function to work. 
All I want to do is record `ctrl + alt + t`  so that I can open a terminal in one button from the f15 button.
Can someone help me out?

Thanks!

**Comment by igorbb** [comment]
If you just want to open the terminal maybe the best is for you to edit the
OS shortcuts. I take that you are using Ubuntu. You will find a lot of
instructions online on how to change keyboard shortcuts.
